# Set up your streams to rtsp here.
port: "8554"
streams: # Cannot rename - must leave this as is.
    stream-rs:
      type: topic
      #source: /kingdom_image_repeater/image_out
      source: /camera/color/image_raw
      mountpoint: /rs-raw
      caps: video/x-raw,framerate=10/1,width=640,height=480
      bitrate: 150

    stream-left:
      type: topic
      source: /sensors/left_camera/image_raw
      mountpoint: /left-raw
      caps: video/x-raw,framerate=10/1,width=640,height=480
      bitrate: 150

    stream-right:
      type: topic
      source: /sensors/right_camera/image_raw
      mountpoint: /right-raw
      caps: video/x-raw,framerate=10/1,width=640,height=480
      bitrate: 150
