# Set up your streams to rtsp here.
port: "8554"
streams: # Cannot rename - must leave this as is.

#  stream-x:
#    type: cam
#    source: "v4l2src device=/dev/video0 ! videoconvert ! videoscale ! video/x-raw,framerate=15/1,width=1280,height=720"
#    mountpoint: /back
#    bitrate: 500

  stream-front:
    type: topic
    source: /sensors/front_camera/image/raw
    mountpoint: /front
    caps: video/x-raw,framerate=10/1,width=640,height=480
    bitrate: 100

  stream-rs:
    type: topic
    source: /camera/color/image_raw
#    source: /camera/color/image_raw/compressed
#    source: /camera/depth/image_rect_raw
    mountpoint: /realsense
    caps: video/x-raw,framerate=10/1,width=640,height=480
    bitrate: 150
